
version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*,localhost,backend
      - DATABASE_URL=sqlite:///db.sqlite3

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - ./menu-frontend/.env.local    
    ports:
      - "3000:3000"
    depends_on:
      - backend








