
# Stage 1: Install dependencies & build
FROM node:18 AS builder

WORKDIR /app

COPY menu-frontend/package*.json ./
RUN npm install

COPY menu-frontend/ .
RUN npm run build

# Stage 2: Run with node
FROM node:18

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 3000

CMD ["npm", "run", "start"]


