version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: menu-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: django-api-nextjs-backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    container_name: django-api-nextjs-frontend
    restart: unless-stopped
    
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:


