apiVersion: v1
kind: Service
metadata:
  name: django-api-nextjs-backend
  namespace: menu-app
spec:
  selector:
    app: django-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

