apiVersion: v1
kind: ConfigMap
metadata:
  name: django-entrypoint-configmap
  namespace: menu-app
data:
  entrypoint.sh: |
    #!/usr/bin/env bash
    set -e

   
    
    if [ -n "${POSTGRES_HOST}" ]; then
      echo "⏳ Waiting for PostgreSQL at ${POSTGRES_HOST}:${POSTGRES_PORT}..."
      /usr/local/bin/postgres.sh
    else
      echo "⚠️ POSTGRES_HOST is not set. Skipping PostgreSQL wait."
    fi
    

    echo "🛠  migrate" && python manage.py migrate --no-input

    echo "📦  collectstatic" && python manage.py collectstatic --no-input

    echo "🚀  gunicorn"
    exec gunicorn RestaurantCore.wsgi:application \
      --bind 0.0.0.0:8000 \
      --workers "${GUNICORN_WORKERS:-3}"
