apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: menu-app
spec:
  type: NodePort
  selector:
    app: nextjs-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000  # You can change this to another available port in range 30000-32767

